CREATE TABLE IF NOT EXISTS Clients
(
  Id         INT PRIMARY KEY AUTO_INCREMENT,
  Email      VARCHAR(100) NOT NULL,
  Password   VARCHAR(60)  NOT NULL,
  FirstName  VARCHAR(100) NOT NULL,
  SecondName VARCHAR(100) NOT NULL,
  Role       VARCHAR(20)  NOT NULL
);