CREATE TABLE STATISTIC_CLIENT
(
  STATISTIC_ID   INT NOT NULL,
  CLIENT_ID      INT NOT NULL,

  CONSTRAINT STATISTICS_STATISTIC_ID_FK  FOREIGN KEY (STATISTIC_ID)  REFERENCES STATISTICS (ID),
  CONSTRAINT CLIENTS_CLIENT_ID_FK  FOREIGN KEY (CLIENT_ID)  REFERENCES CLIENTS (ID)

);